// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xujaxssbncobmiwxbaxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1amF4c3NibmNvYm1pd3hiYXhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzYxODcsImV4cCI6MjA3MDgxMjE4N30.OIGcn1R0Nb8noYAS1I9Mmo-8jUdEndOHY7xfkgk3WfY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});